<?php

/**
* Implementation of hook_form_alter()
*/
function hosting_backup_nogzip_form_alter(&$form, $form_state, $form_id) {
  if (($form_id == 'hosting_task_confirm_form') && user_access('create backup task')) {
    $task_name = $form['task']['#value'];

    if (in_array($task_name, array('backup', 'migrate', 'clone'))) {
      $form['parameters']['nogzip'] = array(
        '#type' => 'checkbox',
        '#title' => t('Do not use gzip for this backup.'),
        '#description' => t('If checked, the archive will not be compressed. This makes the task less resource-intensive, but will take up much more space (probably 5-10x).'),
        '#default_value' => FALSE,
        '#weight' => 5,
      );
    }

    $form['#submit'][] = 'hosting_backup_nogzip_form_submit';

    return $form;
  }
}
